export { default as Home} from './Home'
export { default as Weather} from './Weather'
export { default as Cities} from './Cities'
export { default as Map} from './Map'
export { default as Contact} from './Contact'
